### ISSUE TITLE
Add travis-ci

### ISSUE THREAD

**Issue by yuka1981** [SlackClone/slack_clone#19]
## Travis-CI
[Travis-CI 官網](https://travis-ci.com/)
[參考範例](https://medium.com/@riverye/%E5%A6%82%E4%BD%95%E5%9C%A8-github-%E8%A8%AD%E5%AE%9A-travis-ci-%E4%BB%A5-ruby-on-rails-%E5%B0%88%E6%A1%88%E7%82%BA%E4%BE%8B-7ba227b1d579)

## Tasks
- [ ] 在專案目錄下新增 `.travis.yml` 檔案
- [ ] 在 travis-ci 官網註冊帳號
- [ ] 連結 travis-ci 與 Github 
- [ ] 撰寫 travis-ci 腳本
- [ ] 發 PR 測試 travis-ci 腳本是否正常運作

**Comment by DC7806** [comment]
Ref for caching: https://docs.travis-ci.com/user/caching/#bundler
